#!/bin/bash
HADOOP_CONFIG=/home/hdfs/hadoop_configs/xdata-highmem-config/
$HADOOP_HOME/bin/hadoop --config $HADOOP_CONFIG jar $HADOOP_HOME/share/hadoop/mapreduce1/contrib/streaming/hadoop-streaming-2.0.0-mr1-cdh4.4.0.jar \
-input /tmp/case/input/trivial_text/ \
-output /tmp/akwc/ \
-mapper /bin/cat \
-reducer /usr/bin/wc
